version: '3.5'

networks:
  reverse-proxy:
    external:
      name: ${COMPOSE_NETWORK_REVERSE_PROXY}

services:

  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    image: schmunk42/nginx-redirect:1.0.0-rc1
    restart: ${COMPOSE_RESTART}
    environment:
      SERVER_REDIRECT: github.com/alexandre-abrioux
      SERVER_REDIRECT_CODE: 302
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${COMPOSE_NETWORK_REVERSE_PROXY}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.entrypoints=websecure"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
