version: '3.5'

networks:
  reverse-proxy:
    external:
      name: ${COMPOSE_NETWORK_REVERSE_PROXY}

services:

  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    image: schmunk42/nginx-redirect
    restart: ${COMPOSE_RESTART}
    environment:
      SERVER_REDIRECT: github.com/alexandre-abrioux
      SERVER_REDIRECT_CODE: 302
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOST}"
      - "traefik.docker.network=${COMPOSE_NETWORK_REVERSE_PROXY}"
      - "traefik.port=80"
